[tool.taskipy.tasks]
test = "pytest"
test-chromium = "pytest --browser chromium"
test-webkit = "pytest --browser webkit"
test-firefox = "pytest --browser firefox"
test-all = "pytest --browser chromium --browser firefox --browser webkit"
